version: '3.8'

services:
  app13:
    build:
      context: ./app13
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: go-backend-app13
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 