version: '3.8'

services:
  app12:
    build:
      context: ./app12
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: go-backend-app12
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - uploads-data:/app/uploads
    networks:
      - app-network

volumes:
  uploads-data:
    driver: local

networks:
  app-network:
    driver: bridge 